#!/bin/bash

if [ ! -f /data/uuid.txt ]; then
    cat /proc/sys/kernel/random/uuid > /data/uuid.txt
fi

if [ ! -f /data/serial.txt ]; then
    printf '%02X%02X%02X%02X%02X%02X\n' $[RANDOM%256] $[RANDOM%256] $[RANDOM%256] $[RANDOM%256] $[RANDOM%256] $[RANDOM%256] > /data/serial.txt
fi

if [ "$1" == "id" ]; then
    if [ -n "$2" ]; then
        if [ -f "$2" ]; then
            cat "$2"
            exit 0
        fi
        touch $2
        echo "board.sysid=0xea16" >> "$2" # UNVR4
        echo "board.uuid=$(cat /data/uuid.txt)" >> "$2"
        echo "board.name=UniFi Network Video Recorder" >> "$2"
        echo "board.shortname=UNVR" >> "$2"
        echo "board.hwrev=1" >> "$2"
        echo "board.serialno=$(cat /data/serial.txt)" >> "$2"

    fi
    echo "board.sysid=0xea16" # UNVR4
    echo "board.uuid=$(cat /data/uuid.txt)"
    echo "board.name=UniFi Network Video Recorder"
    echo "board.shortname=UNVR"
    echo "board.hwrev=1"
    echo "board.serialno=$(cat /data/serial.txt)"
elif [ "$1" == "uuid" ]; then
    cat /data/uuid.txt
elif [ -z ${1+x} ]; then
    echo "ubnt-tools copycat"
else
    echo "Unknown ubnt-tools cmd: $@" >> /tmp/ubnt-tools-unknown.log
fi
